Feat/33 적용 완료
dkdace/dmgr-server pull request #37
Opened 2022-11-06 02:23 UTC by DoubleDeltas

치명타 적용 및 ArkaceWeapon에 적용해봄

테스트 안해봄

2022-11-08 16:14 UTC, dkdace requested changes
getNearEnemies 메소드에는 치명타 판정이 필요하지 않음

2022-11-08 16:14 UTC, dkdace commented on src/main/java/com/dace/dmgr/combat/Combat.java
> +        if (LocationUtil.isInHitbox(location, entity.getCritHitbox(), range)) {
50-56줄 이렇게 줄이는 건 어떨까요
```java
return new AbstractMap.SimpleEntry<>(entity,
LocationUtil.isInHitbox(location, entity.getCritHitbox(), range) ? true : 
LocationUtil.isInHitbox(location, entity.getHitbox(), range));
```

2022-11-10 05:37 UTC, DoubleDeltas commented on src/main/java/com/dace/dmgr/combat/entity/CombatUser.java
> +                new Hitbox(entity.getLocation(), 0, entity.getHeight() * 0.83, 0, 0.4, 0.2, 0.4)
1.8이면 offset이 머리카락 끝인디요

2022-11-10 05:37 UTC, DoubleDeltas commented on src/main/java/com/dace/dmgr/combat/Bullet.java
>      public abstract void onHitEntity(Location location, ICombatEntity target);
확인

2022-11-10 05:38 UTC, DoubleDeltas commented on src/main/java/com/dace/dmgr/combat/Combat.java
> +    public static Map<ICombatEntity, Boolean> getNearEnemies(ICombatEntity attacker, Location location, float range) {
확장성을 고려한 거긴 한데 일단 ㅇㅋ 롤백해놓겠음

2022-11-10 05:42 UTC, DoubleDeltas commented on src/main/java/com/dace/dmgr/combat/Combat.java
> +        if (LocationUtil.isInHitbox(location, entity.getCritHitbox(), range)) {
crit -> true / hit -> true / not hit -> false 가 아니라
crit -> true / hit -> false / not hit -> return null 임

2022-11-10 12:47 UTC, dkdace commented on src/main/java/com/dace/dmgr/combat/Combat.java
> +        if (LocationUtil.isInHitbox(location, entity.getCritHitbox(), range)) {
ㅈㅅ 착각함

2022-11-10 12:49 UTC, dkdace commented on src/main/java/com/dace/dmgr/combat/entity/CombatUser.java
> +                new Hitbox(entity.getLocation(), 0, entity.getHeight() * 0.83, 0, 0.4, 0.2, 0.4)
이건 나중에 테스트 해볼게여

2022-11-11 17:35 UTC, merged